# This literally does nothing
# I just wanted something familiar to BIOS stuff
# I'm relying on UEFI's GDT
# I kinda miss BIOS stuff
# Doing C for a bootloader felt weird
# BTW, I'm built different lol
# Also, x86 assembly is significantly better than NASM, YASM, or any other assembly language where you put a letter in front of ASM
# C is the goat, but it still feels unnatural for the bootloader
# Bread is peak
# Bread is peak
# Bread is peak
# CLIs are better than GUIs
# I forgot what I was going to say next
# THE WORLD WAS MISERABLE IN 1492!!!!!!!!!!!!!!!!!!!!!!!!!
# If you're looking at this, please don't leave, I have no friends.
# Remember, reality is an illusion, the universe is a hologram, buy gold, BYE

# I am back here for some reason
# Also, CinnamonOS (CMOS) has nothing to do with the Linux desktop environment 
# That's basically all I wanted to say
